### ISSUE TITLE
ModuleNotFoundError: No module named 'face_alignment.models'

### ISSUE THREAD

**Issue by Yueming6568** [FuxiCV/MeInGame#10]
Thanks for sharing your great work

I got some error when run the code

`python main.py -m train`

![image](https://user-images.githubusercontent.com/75259961/109739316-6455f380-7c04-11eb-8d38-d550b2e1305d.png)

**Comment by Yueming6568** [comment]
I can not find those files

`from face_alignment.models import FAN, ResNetDepth
from face_alignment.utils import *`

**Comment by Agent-INF** [comment]
@Yueming6568 This may be caused by an incompatible version of the face-alignment package.
Please try to uninstall it:
```
pip uninstall face-alignment
```
and then reinstall it:
```
pip install face-alignment==1.1.1
```

**Comment by Yueming6568** [comment]
> @Yueming6568 This may be caused by an incompatible version of the face-alignment package.
> Please try to uninstall it:
> 
> ```
> pip uninstall face-alignment
> ```
> 
> and then reinstall it:
> 
> ```
> pip install face-alignment==1.1.1
> ```

**Comment by Yueming6568** [comment]
thank you for your answer! It helped me a lot
