### ISSUE TITLE
landmarks 坐标点如何选择

### ISSUE THREAD

**Issue by arixlin** [FuxiCV/MeInGame#26]
你好，shape transfer 时 landmarks 坐标点如何选择 index是使用什么软件查看的 blender 还是maya
`
tgt_ref = meshio.Mesh(os.path.join(tgt_dir, 'deformed.obj'))
`
`
self.lm_idx = np.loadtxt(os.path.join(tgt_dir, 'landmarks.txt'), dtype=np.int32)
`

**Comment by chenxhhh** [comment]
我这边是用maya查看landmarks的。话说你有试过训练代码么，我看到了你提的另一个issue里面解决了dataloader多线程bug。

**Comment by arixlin** [comment]
@chenxhhh 好的 谢谢！  我用的是blender index是一致的
