### ISSUE TITLE
weird Texture

### ISSUE THREAD

**Issue by t-qureshi** [FuxiCV/MeInGame#3]
Hi @FuxiCV thanks for sharing your great project. I am getting weird textures when i implement your repo. Would you mind to tell where i am doing mistake. 
input Image:
![000_input](https://user-images.githubusercontent.com/61450584/107476344-78737b80-6b97-11eb-9c03-8427dd830125.jpg)
Texture made:
![000_uv](https://user-images.githubusercontent.com/61450584/107476345-790c1200-6b97-11eb-86f7-ebdaf946f3da.png)

**Comment by Agent-INF** [comment]
Hi @t-qureshi, it looks like the checkpoint file is not loaded correctly, did you download our pre-trained model and put it into the right directory?

**Comment by t-qureshi** [comment]
Thanks @Agent-INF you are right. I missed to set the correct path of pre-trained model.
